lib/discuss_test_web/router.ex
defmodule DiscussTestWeb.Router do
  use DiscussTestWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {DiscussTestWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", DiscussTestWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/topics/new", TopicController, :new
    post "/topics", TopicController, :create
  end

  # Other scopes may use custom stacks.
  # scope "/api", DiscussTestWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: DiscussTestWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/discuss_test/application.ex
defmodule DiscussTest.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  @impl true
  def start(_type, _args) do
    children = [
      # Start the Ecto repository
      DiscussTest.Repo,
      # Start the Telemetry supervisor
      DiscussTestWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: DiscussTest.PubSub},
      # Start the Endpoint (http/https)
      DiscussTestWeb.Endpoint
      # Start a worker by calling: DiscussTest.Worker.start_link(arg)
      # {DiscussTest.Worker, arg}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: DiscussTest.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  @impl true
  def config_change(changed, _new, removed) do
    DiscussTestWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/discuss_test/mailer.ex
defmodule DiscussTest.Mailer do
  use Swoosh.Mailer, otp_app: :discuss_test
end

lib/discuss_test/repo.ex
defmodule DiscussTest.Repo do
  use Ecto.Repo,
    otp_app: :discuss_test,
    adapter: Ecto.Adapters.Postgres
end

lib/discuss_test_web/controllers/page_controller.ex
defmodule DiscussTestWeb.PageController do
  use DiscussTestWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/discuss_test_web/controllers/topic_controller.ex
defmodule DiscussTestWeb.TopicController do
  use DiscussTestWeb, :controller

  alias DiscussTestWeb.Topic

  def new(conn, _params) do
    changeset = Topic.changeset(%Topic{}, %{})

    render(conn, "new.html", changeset: changeset)
  end

end

lib/discuss_test_web/views/error_view.ex
defmodule DiscussTestWeb.ErrorView do
  use DiscussTestWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/discuss_test_web/views/layout_view.ex
defmodule DiscussTestWeb.LayoutView do
  use DiscussTestWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/discuss_test_web/views/page_view.ex
defmodule DiscussTestWeb.PageView do
  use DiscussTestWeb, :view
end

lib/discuss_test_web/views/topic_view.ex
alias DiscussWeb.Router.Helpers, as: Routes

defmodule DiscussTestWeb.TopicView do
  use DiscussTestWeb, :view
end

lib/discuss_test_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/discuss_test_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/discuss_test_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="csrf-token" content={csrf_token_value()}>
    <script src="https://cdn.tailwindcss.com"></script>
    <%= live_title_tag assigns[:page_title] || "DiscussTest", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"/>
  </head>
  <body>
    <nav class = "light-blue">
      <div class="nav-wrapper container">
        <a href="/" class="brand-logo">
          Discussions
        </a>
      </div>
    </nav>

    <%= @inner_content %>
  </body>
</html>

lib/discuss_test_web/templates/page/index.html.heex
<h5> Topics </h5>

<section class="row">
  <article class="column">
    <h2>Resources</h2>
    <ul>
      <li>
        <a href="https://hexdocs.pm/phoenix/overview.html">Guides &amp; Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix/blob/v1.6/CHANGELOG.md">v1.6 Changelog</a>
      </li>
    </ul>
  </article>
  <article class="column">
    <h2>Help</h2>
    <ul>
      <li>
        <a href="https://elixirforum.com/c/phoenix-forum">Forum</a>
      </li>
      <li>
        <a href="https://web.libera.chat/#elixir">#elixir on Libera Chat (IRC)</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">Twitter @elixirphoenix</a>
      </li>
      <li>
        <a href="https://elixir-slackin.herokuapp.com/">Elixir on Slack</a>
      </li>
      <li>
        <a href="https://discord.gg/elixir">Elixir on Discord</a>
      </li>
    </ul>
  </article>
</section>

lib/discuss_test_web/templates/topic/new.html.heex
<%= form_for @changeset, Routes.topic_path(@conn, :create), fn f -> %>

<div class="form-group"> 
    <% text_input f, :title, placeholder: "Title", class: "form-control" %>
</div>

<%=submit "Save Topic", class: "btn btn-primary" %>
<% end %>